@server = http://localhost:4004
 
### Get all books
GET {{server}}/odata/v4/catalog/Books
Authorization: Basic user1@example.com:initial
 
### Get all authors
GET {{server}}/odata/v4/catalog/Authors
 
### Create new author
POST {{server}}/odata/v4/catalog/Authors
Content-Type: application/json
 
{
  "ID": 200,
  "name": "William Shakespeare",
  "dateOfBirth": "1564-04-26"
}

### Get total stock
GET {{server}}/odata/v4/catalog/totalStock()


### Submit an order
POST {{server}}/odata/v4/catalog/submitOrder
Content-Type: application/json

{ "book":207, "quantity":1 }

### Create new book
POST {{server}}/odata/v4/catalog/Books
Content-Type: application/json
Authorization: Basic user1@example.com:initial

{
  "ID": 299,
  "title": "The Fall of the House of Ushe",
  "author_ID": 150,
  "stock":67,
  "price": 19.19
}